export const TOGGLE_STOPWATCH = 'TOGGLE_STOPWATCH';
export type TOGGLE_STOPWATCH = typeof TOGGLE_STOPWATCH;

export const RESET_STOPWATCH = 'RESET_STOPWATCH';
export type RESET_STOPWATCH = typeof RESET_STOPWATCH;